USE GrupoSerena;
CREATE table if not exists CLIENTES
(ID_CLIENTE INT primary key NOT NULL, 
NOMBRE varchar (30) NOT NULL,
APELLIDO varchar (30) NOT NULL,
DNI INT NOT NULL,
EMAIL varchar (30) NOT NULL,
CELULAR INT NOT NULL);

CREATE table if not exists COBROS
(ID_COBRO INT primary key NOT NULL,
MONTO FLOAT NOT NULL,
FECHA DATE NOT NULL,
FORMA_DEPAGO varchar (30) NOT NULL,
CUOTA INT NOT NULL); 

CREATE table if not exists DIRECCION
(ID_DIRECCION INT primary key NOT NULL,
CALLE varchar (50) NOT NULL,
NRO_CALLE INT NULL,
LOCALIDAD varchar (50) NOT NULL,
PROVINCIA varchar (50) NOT NULL,
PAIS varchar (50) NOT NULL); 

CREATE table if not exists FACTURAS
(ID_FACTURA INT primary key NOT NULL,
NUM_FACT INT NOT NULL,
PRECIO FLOAT NOT NULL,
TIPO_FACTURA varchar (20) NOT NULL,
IMPUESTO INT NOT NULL);

CREATE table if not exists EDIFICIOS
(ID_EDIFICIO varchar (30) primary key NOT NULL,
NOMBRE_EDIFICIO varchar (30) NOT NULL,
DIRECCION INT,
CANT_DPTOS INT NOT NULL,
foreign key (DIRECCION) references DIRECCION (ID_DIRECCION));

CREATE table if not exists DEPARTAMENTOS
(ID_DEPARTAMENTO INT primary key NOT NULL,
EDIFICIO varchar (30),
PRECIO FLOAT NOT NULL,
foreign key (EDIFICIO) references EDIFICIOS (ID_EDIFICIO)); 

CREATE table if not exists VENTAS
(ID_VENTA INT primary key NOT NULL,
CLIENTE INT,
COBRO INT,
DEPARTAMENTO INT,
FECHA DATE NOT NULL,
FACTURA INT,
foreign key (CLIENTE) references CLIENTES (ID_CLIENTE),
foreign key (COBRO) references COBROS (ID_COBRO),
foreign key (DEPARTAMENTO) references DEPARTAMENTOS (ID_DEPARTAMENTO),
foreign key (FACTURA) references FACTURAS (ID_FACTURA));


